syntax = "proto3";

option go_package = "github.com/cirruslabs/orchard/rpc";

message WatchInstruction {
  message PortForward {
    // we can have multiple port forwards for the same vm/port pair
    // let's distinguish them by a unique session
    string session = 1;
    // can be empty to request port-forwarding to the worker itself
    string vm_uid = 2;
    uint32 port = 3;
  }
  message SyncVMs {
    // nothing for now
  }
  message ResolveIP {
    // we can have multiple IP resolution requests for the same vm
    // let's distinguish them by a unique session
    string session = 1;
    string vm_uid = 2;
  }

  oneof action {
    PortForward port_forward_action = 1;
    SyncVMs sync_vms_action = 2;
    ResolveIP resolve_ip_action = 3;
  }
}

message PortForwardData {
  bytes data = 1;
}

message ResolveIPResult {
  string session = 1;
  string ip = 2;
}
