// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orchard.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchInstruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*WatchInstruction_PortForwardAction
	//	*WatchInstruction_SyncVmsAction
	//	*WatchInstruction_ResolveIpAction
	Action        isWatchInstruction_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchInstruction) Reset() {
	*x = WatchInstruction{}
	mi := &file_orchard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchInstruction) ProtoMessage() {}

func (x *WatchInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchInstruction.ProtoReflect.Descriptor instead.
func (*WatchInstruction) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{0}
}

func (x *WatchInstruction) GetAction() isWatchInstruction_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *WatchInstruction) GetPortForwardAction() *WatchInstruction_PortForward {
	if x != nil {
		if x, ok := x.Action.(*WatchInstruction_PortForwardAction); ok {
			return x.PortForwardAction
		}
	}
	return nil
}

func (x *WatchInstruction) GetSyncVmsAction() *WatchInstruction_SyncVMs {
	if x != nil {
		if x, ok := x.Action.(*WatchInstruction_SyncVmsAction); ok {
			return x.SyncVmsAction
		}
	}
	return nil
}

func (x *WatchInstruction) GetResolveIpAction() *WatchInstruction_ResolveIP {
	if x != nil {
		if x, ok := x.Action.(*WatchInstruction_ResolveIpAction); ok {
			return x.ResolveIpAction
		}
	}
	return nil
}

type isWatchInstruction_Action interface {
	isWatchInstruction_Action()
}

type WatchInstruction_PortForwardAction struct {
	PortForwardAction *WatchInstruction_PortForward `protobuf:"bytes,1,opt,name=port_forward_action,json=portForwardAction,proto3,oneof"`
}

type WatchInstruction_SyncVmsAction struct {
	SyncVmsAction *WatchInstruction_SyncVMs `protobuf:"bytes,2,opt,name=sync_vms_action,json=syncVmsAction,proto3,oneof"`
}

type WatchInstruction_ResolveIpAction struct {
	ResolveIpAction *WatchInstruction_ResolveIP `protobuf:"bytes,3,opt,name=resolve_ip_action,json=resolveIpAction,proto3,oneof"`
}

func (*WatchInstruction_PortForwardAction) isWatchInstruction_Action() {}

func (*WatchInstruction_SyncVmsAction) isWatchInstruction_Action() {}

func (*WatchInstruction_ResolveIpAction) isWatchInstruction_Action() {}

type PortForwardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardData) Reset() {
	*x = PortForwardData{}
	mi := &file_orchard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardData) ProtoMessage() {}

func (x *PortForwardData) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardData.ProtoReflect.Descriptor instead.
func (*PortForwardData) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{1}
}

func (x *PortForwardData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResolveIPResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIPResult) Reset() {
	*x = ResolveIPResult{}
	mi := &file_orchard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIPResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIPResult) ProtoMessage() {}

func (x *ResolveIPResult) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIPResult.ProtoReflect.Descriptor instead.
func (*ResolveIPResult) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveIPResult) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ResolveIPResult) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type WatchInstruction_PortForward struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// we can have multiple port forwards for the same vm/port pair
	// let's distinguish them by a unique session
	Session string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// can be empty to request port-forwarding to the worker itself
	VmUid         string `protobuf:"bytes,2,opt,name=vm_uid,json=vmUid,proto3" json:"vm_uid,omitempty"`
	Port          uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchInstruction_PortForward) Reset() {
	*x = WatchInstruction_PortForward{}
	mi := &file_orchard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchInstruction_PortForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchInstruction_PortForward) ProtoMessage() {}

func (x *WatchInstruction_PortForward) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchInstruction_PortForward.ProtoReflect.Descriptor instead.
func (*WatchInstruction_PortForward) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WatchInstruction_PortForward) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *WatchInstruction_PortForward) GetVmUid() string {
	if x != nil {
		return x.VmUid
	}
	return ""
}

func (x *WatchInstruction_PortForward) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type WatchInstruction_SyncVMs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchInstruction_SyncVMs) Reset() {
	*x = WatchInstruction_SyncVMs{}
	mi := &file_orchard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchInstruction_SyncVMs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchInstruction_SyncVMs) ProtoMessage() {}

func (x *WatchInstruction_SyncVMs) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchInstruction_SyncVMs.ProtoReflect.Descriptor instead.
func (*WatchInstruction_SyncVMs) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{0, 1}
}

type WatchInstruction_ResolveIP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// we can have multiple IP resolution requests for the same vm
	// let's distinguish them by a unique session
	Session       string `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	VmUid         string `protobuf:"bytes,2,opt,name=vm_uid,json=vmUid,proto3" json:"vm_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchInstruction_ResolveIP) Reset() {
	*x = WatchInstruction_ResolveIP{}
	mi := &file_orchard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchInstruction_ResolveIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchInstruction_ResolveIP) ProtoMessage() {}

func (x *WatchInstruction_ResolveIP) ProtoReflect() protoreflect.Message {
	mi := &file_orchard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchInstruction_ResolveIP.ProtoReflect.Descriptor instead.
func (*WatchInstruction_ResolveIP) Descriptor() ([]byte, []int) {
	return file_orchard_proto_rawDescGZIP(), []int{0, 2}
}

func (x *WatchInstruction_ResolveIP) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *WatchInstruction_ResolveIP) GetVmUid() string {
	if x != nil {
		return x.VmUid
	}
	return ""
}

var File_orchard_proto protoreflect.FileDescriptor

const file_orchard_proto_rawDesc = "" +
	"\n" +
	"\rorchard.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x03\n" +
	"\x10WatchInstruction\x12O\n" +
	"\x13port_forward_action\x18\x01 \x01(\v2\x1d.WatchInstruction.PortForwardH\x00R\x11portForwardAction\x12C\n" +
	"\x0fsync_vms_action\x18\x02 \x01(\v2\x19.WatchInstruction.SyncVMsH\x00R\rsyncVmsAction\x12I\n" +
	"\x11resolve_ip_action\x18\x03 \x01(\v2\x1b.WatchInstruction.ResolveIPH\x00R\x0fresolveIpAction\x1aR\n" +
	"\vPortForward\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x15\n" +
	"\x06vm_uid\x18\x02 \x01(\tR\x05vmUid\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x1a\t\n" +
	"\aSyncVMs\x1a<\n" +
	"\tResolveIP\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x15\n" +
	"\x06vm_uid\x18\x02 \x01(\tR\x05vmUidB\b\n" +
	"\x06action\"%\n" +
	"\x0fPortForwardData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\";\n" +
	"\x0fResolveIPResult\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip2\xb0\x01\n" +
	"\n" +
	"Controller\x124\n" +
	"\x05Watch\x12\x16.google.protobuf.Empty\x1a\x11.WatchInstruction0\x01\x125\n" +
	"\vPortForward\x12\x10.PortForwardData\x1a\x10.PortForwardData(\x010\x01\x125\n" +
	"\tResolveIP\x12\x10.ResolveIPResult\x1a\x16.google.protobuf.EmptyB#Z!github.com/cirruslabs/orchard/rpcb\x06proto3"

var (
	file_orchard_proto_rawDescOnce sync.Once
	file_orchard_proto_rawDescData []byte
)

func file_orchard_proto_rawDescGZIP() []byte {
	file_orchard_proto_rawDescOnce.Do(func() {
		file_orchard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchard_proto_rawDesc), len(file_orchard_proto_rawDesc)))
	})
	return file_orchard_proto_rawDescData
}

var file_orchard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_orchard_proto_goTypes = []any{
	(*WatchInstruction)(nil),             // 0: WatchInstruction
	(*PortForwardData)(nil),              // 1: PortForwardData
	(*ResolveIPResult)(nil),              // 2: ResolveIPResult
	(*WatchInstruction_PortForward)(nil), // 3: WatchInstruction.PortForward
	(*WatchInstruction_SyncVMs)(nil),     // 4: WatchInstruction.SyncVMs
	(*WatchInstruction_ResolveIP)(nil),   // 5: WatchInstruction.ResolveIP
	(*emptypb.Empty)(nil),                // 6: google.protobuf.Empty
}
var file_orchard_proto_depIdxs = []int32{
	3, // 0: WatchInstruction.port_forward_action:type_name -> WatchInstruction.PortForward
	4, // 1: WatchInstruction.sync_vms_action:type_name -> WatchInstruction.SyncVMs
	5, // 2: WatchInstruction.resolve_ip_action:type_name -> WatchInstruction.ResolveIP
	6, // 3: Controller.Watch:input_type -> google.protobuf.Empty
	1, // 4: Controller.PortForward:input_type -> PortForwardData
	2, // 5: Controller.ResolveIP:input_type -> ResolveIPResult
	0, // 6: Controller.Watch:output_type -> WatchInstruction
	1, // 7: Controller.PortForward:output_type -> PortForwardData
	6, // 8: Controller.ResolveIP:output_type -> google.protobuf.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_orchard_proto_init() }
func file_orchard_proto_init() {
	if File_orchard_proto != nil {
		return
	}
	file_orchard_proto_msgTypes[0].OneofWrappers = []any{
		(*WatchInstruction_PortForwardAction)(nil),
		(*WatchInstruction_SyncVmsAction)(nil),
		(*WatchInstruction_ResolveIpAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchard_proto_rawDesc), len(file_orchard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchard_proto_goTypes,
		DependencyIndexes: file_orchard_proto_depIdxs,
		MessageInfos:      file_orchard_proto_msgTypes,
	}.Build()
	File_orchard_proto = out.File
	file_orchard_proto_goTypes = nil
	file_orchard_proto_depIdxs = nil
}
